title: "최병호의 블로그"
description: "Lifes like ..."
url: "https://byunghochoi.github.io"
baseurl: ""
repository: "ByungHoChoi/ByungHoChoi.github.io"

author:
  name: "bhchoi"
  avatar: "/assets/image_profile/1_p6ClFuTDD-iqvcTTdX1DHA.jpeg"
  bio: "AI, Computer System"
  location: "Seoul, Korea"
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/ByungHoChoi"

theme: minimal-mistakes-jekyll
minimal_mistakes_skin: "air"
locale: "en-US"
search: true
breadcrumbs: true

permalink: /:categories/:year/:month/:day/:title/

plugins:
  - jekyll-include-cache

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "single"
      author_profile: true
      read_time: true
      comments: false
      share: false
      related: true

markdown: kramdown
highlighter: rouge

exclude:
  - examples/
  - vendor/
